### ISSUE TITLE
eventListeners attached to the rows WILL be removed

### ISSUE THREAD

**Issue by mattiapontonio** [tofsjonas/sortable#13]
I'm looking to a solution to this.
Maybe using `remove` and `append` child methods works (actually not tested).

See
https://jsfiddle.net/jmarikle/vxju87nv/

P.s. HTMLCollection is returned by the `rows` of the interface of `tbody`.

https://github.com/mdn/sprints/issues/3781

**Comment by mattiapontonio** [comment]
Actually are preserved: https://jsfiddle.net/mjsfr163/1/

**Comment by mattiapontonio** [comment]
https://gist.github.com/mattiapontonio/41ba0e2ab2ab04b130aff1edbc2d0969

**Comment by tofsjonas** [comment]
It's been a while since I wrote this, so I don't really remember why I did what I did. 😬🤔

(I haven't had any use for this in quite some time, so if you hadn't taken an interest I doubt if I would have ever touched it again...)

I think one of my main concerns at the time was to limit the interaction with the "real" dom. I seem to remember blinks and rows moving up and down, making it look kind of funny.

That's why I cloned the table body, so I could work in a "virtual" dom on that instead. I also had my own sorting-function, since HTMLCollection doesn't implement "sort", like arrays do.


Did I understand you right, that eventlisteners still work? I guess that could be a consequence of no longer making a clone 🤔

When I started using array.sort instead, I forgot to remove the cloning. I haven't tested the consequences of any of this, but if they do that is super cool 😎

**Comment by mattiapontonio** [comment]
I think that listeners are attatched THE object in the DOM so another object is "disconnected in memory".
The Virtual DOM i don't know... I know that some libraries use this concept but onestly I like ti know and use the platform "as is" of I Can.
So no needs to mandatory fix of course. If You want You can close the fix i just want to informe here because It was a problem that i has tackled.

**Comment by mattiapontonio** [comment]
P.s. inspired to that issue i've Just contributed to this page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table see sorting section.
