### ISSUE TITLE
Why using a regex to detect sortable class?

### ISSUE THREAD

**Issue by G2G2G2G** [tofsjonas/sortable#23]
`e.classList.contains('sortable')`  ?

I've tested (and this is hilarious with the parentnodes):
```
if(!b.parentNode.parentNode.parentNode.classList.contains('sortable')){return;}
```
before the "try" you use, which works fine, this throws out the function instead of running a bunch of stuff unnecessarily. I'd wrap the entire thing in the if statement without the ! probably

**Comment by tofsjonas** [comment]
Not that it really matters anymore, but `classList` is not supported by ie9, and I like that it is ie9+ 🤓🤷

As for the `parentNode.parentNode...` approach, that wouldn't work if there are nested elements inside the `th`, like [mxve](https://github.com/mxve) pointed out.

Also I figured I should have a try-catch, since sortable can't know what other scripts are running, or even what the html looks like. And while it's there, why not use it?

**Comment by G2G2G2G** [comment]
I see thanks, just making sure I wasn't missing anything (no idea who mxve is either :^) ) 

Also switched to `b.target.parentElement.parentElement.parentElement.classList.Contains`(b is the event (e) in the minified version) if anyone stumbles on this thread ever

**Comment by tofsjonas** [comment]
Thanks for taking an interest!
