### ISSUE TITLE
Sort by anything other then string

### ISSUE THREAD

**Issue by Macro-Jackson** [tofsjonas/sortable#5]
Nice simple sort tool. But it can't handle anything special it seems. Can't sort by date or memory size or version number.....

So would be nice to add some of these as an option.

**Comment by tofsjonas** [comment]
Well, since this line:

`return isNaN( a - b ) ? a.localeCompare( b ) : a - b;`

is the only sorting algorithm there is, I guess there is room for more advanced stuff ;)

Send me some examples of what you would like sorted and I'll look at it. Or if you've already done the work, feel free to make a fork. Or send it over, whichever suits your fancy :)

Appreciate the feedback!

**Comment by Macro-Jackson** [comment]
First of all what would solve many cases is sorting by a td attribute. So a value can be filled in that represents the data in the field.
For example:
0.004 for 4kB
10 for 10MB
120000 for 120GB
etc

In many cases the developer knows what the data represents he just wants to make it human readable.

**Comment by tofsjonas** [comment]
Added the advanced as well as the mega-advanced version
