### ISSUE TITLE
Sorts fields starting with a dollar sign as text rather than as a number.

### ISSUE THREAD

**Issue by mikeredbike** [tofsjonas/sortable#59]
Version2.3.2 sorts fields beginning with a dollar sign as text rather than as a number.
 
Sortable creates an ascending column as $2.49, $18.49, $1.96; it should be $18.49, $2.49, $1.96.

Checkout  https://juicedude.com/daytrades/

**Comment by tofsjonas** [comment]
One man's bug is another man's feature 😅

`parseFloat` converts $2.49 to 2.49, which is the desired behaviour.

`parseFloat` converts 12:33:56 to 12, which is **NOT** the desired behaviour.

Honestly, I don't know which is better. I need to think about it.

Thanks for bringing it up! 🙏

**Comment by tofsjonas** [comment]
So I had time to look at it.

Turns out I was wrong. parseFloat does NOT convert $2.49 to 2.49, it becomes NaN.

So I _think_ this bug Is probably something else. (I tried with really old versions of sortable)

If you want to sort them correctly, I would recommend either using `data-sort`

```html
<td data-sort="2.49">$2.49</td>
<td data-sort="18.49">$18.49</td>
<td data-sort="1.96">$1.96</td>
```

or by adding the "$" with `CSS`

```html
<td>2.49</td>
<td>18.49</td>
<td>1.96</td>

```
```css
td::before {
  content:'$'
}
```

I hope this helps!
