### ISSUE TITLE
Tables with rowspans not sortable

### ISSUE THREAD

**Issue by coljac** [tofsjonas/sortable#71]
For a table with `rowspan="n"`, the sorting leads to a broken table display. Here's an example:

```
<html><body>
<table class="sortable">
  <thead>
    <tr>
        <th>Class</th>
      <th><span>Role</span></th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td rowspan="2">Main Character</td>
      <td>Aenius</td>
      <td>Bird Person</td>
    </tr>
    <tr>
      <td>Genius</td>
      <td>Rick</td>
    </tr>
    <tr>
        <td>Comic Relief</td>
      <td><a href="javascript:alert('Inline javascript works!');">Sidekick</a></td>
      <td>Morty</td>
    </tr>
  </tbody>
</table>
<link href="/assets/sortable.min.css" rel="stylesheet" />
<script src="/assets/sortable.min.js"></script>
    </body></html>
```

**Expected result**: It treats a rowspan as a single row for sorting purposes.
**Actual result**: The table is scrambled, sometimes columns are added.

![before](https://github.com/tofsjonas/sortable/assets/191407/bf2519b6-c61b-47e4-a931-bc9388fb3b1a)
![after1](https://github.com/tofsjonas/sortable/assets/191407/6eef0450-4084-47cf-a703-79636a4370ea)

**Comment by tofsjonas** [comment]
I have racked my brain trying to figure out a solution, but if it works for this it breaks in other ways. 

The problem with `rowspans` is that they affect the row(s) following the current one. So to not break the table we would have to group them and lock them to that group. This could probably work for the column that has the rowspan, but sorting would break for all the other columns, since they cannot be allowed to split the group.

(Not to mention what would happen if a row has multiple columns with rowspans. Or overlapping rowspans from other rows. 🫣)

I am sorry, but I think it may not even be _theoretically_ possible 🤯😢

**Comment by phil2phil** [comment]
Atomize the row span by duplicating the content in the spanned rows. When sorting, the row span would have to be torn apart. There is no other option.

**Comment by ernstki** [comment]
> Atomize the row span by duplicating the content in the spanned rows. When sorting, the row span would have to be torn apart. There is no other option.

As I recall, this is the approach taken by MediaWiki's sortable tables, too.
